/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIStreamListener.idl"

interface nsIURI;
interface nsICacheEntry;

/**
 * nsIPackagedAppVerifier
 */
[scriptable, builtinclass, uuid(f7611bd0-4c96-11e5-b970-0800200c9a66)]
interface nsIPackagedAppVerifier : nsIStreamListener
{
  // The package origin of either signed or unsigned package.
  readonly attribute ACString packageOrigin;

  // Whether this package is signed.
  readonly attribute boolean isPackageSigned;
};

/**
 * nsIPackagedAppVerifierListener
 */
[scriptable, builtinclass, uuid(00a78760-4c97-11e5-b970-0800200c9a66)]
interface nsIPackagedAppVerifierListener : nsISupports
{
  void onVerified(in boolean aIsManifest,
                  in nsIURI aUri,
                  in nsICacheEntry aCacheEntry,
                  in nsresult aStatusCode,
                  in boolean aIsLastPart,
                  in boolean aVerificationSuccess);
};

