/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(27caf7d0-3c0e-11e5-b970-0800200c9a66)]
interface nsIPackagedAppChannelListener : nsISupports
{
  void onStartSignedPackageRequest(in ACString aNewOrigin);
};
